name: test

on:
  push:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-buildxxs

      - name: Up
        run: |
          docker compose up -d


      - name: Cache Mypy
        uses: actions/cache@v2
        id: mypy
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-mypy

      - name: Mypy
        run: |
          docker compose exec app poetry run mypy src
