name: test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ hashFiles('**/poetry.lock') }}-buildx

      # 最新のbuild cacheのみ残しておきたいのでlocal -> localのbuildを行なう
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Build cache
        run: |
          docker builder build . --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # Github Actionsのdocker composeがbuildxを使ってくれてなさそうなのでイメージビルドはdocker builder bakeで行う
      - name: Up
        run: |
          docker builder bake -f docker-compose.yml --load --set *.cache-from=type=local,src=/tmp/.buildx-cache
          docker compose up -d

      - name: Cache Mypy
        uses: actions/cache@v2
        id: mypy
        with:
          path: .mypy_cache
          key: ${{ hashFiles('**/poetry.lock') }}-mypy

      - name: Mypy
        run: |
          docker compose exec app poetry run mypy src
